os:
  # - linux
  - osx

language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
  homebrew:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
install: true
env:
  matrix:
    # - ARCH=linux_386
    # - ARCH=linux_amd64
    - ARCH=386
    - ARCH=amd64
script:
  - make -f $(go env GOHOSTOS)_${ARCH}.Makefile dist
  - make -f $(go env GOHOSTOS)_${ARCH}.Makefile test-ft
  - make -f $(go env GOHOSTOS)_${ARCH}.Makefile test-ft-hb


