language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
install: true
script:
  # - make -f linux_386.Makefile dist
  # - make -f linux_386.Makefile test-ft
  # - make -f linux_386.Makefile test-ft-hb
  - make -f linux_amd64.Makefile dist
  - make -f linux_amd64.Makefile test-ft
  - make -f linux_amd64.Makefile test-ft-hb


