language: C
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - gcc
    - libc6-dev
    - make
    - pkg-config
compiler: gcc
before_script: sudo apt-get remove zlib
script: make dist-linux