os:
  - linux
  # - osx

language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
    - libtool
  homebrew:
  #  update: true
   packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
install: true
env:
  matrix:
    - ARCH=linux_386
    - ARCH=linux_amd64
    # - ARCH=darwin_386
    # - ARCH=darwin_amd64
script:
  - make -f $ARCH.Makefile dist
  - make -f $ARCH.Makefile test-ft
  - make -f $ARCH.Makefile test-ft-hb


