language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
install: true
env:
  matrix:
    - GOOSARCH=linux_386
    - GOOSARCH=linux_amd64
script:
  - "make -f $GOOSARCH.Makefile dist"
  - "make -f $GOOSARCH.Makefile test-ft"
  - "make -f $GOOSARCH.Makefile test-ft-hb race"


