language: go
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - g++-multilib
    - gcc
    - gcc-multilib
    - libc6-dev
    - libc6-dev-i386
    - make
    - pkg-config
install: true
env:
  matrix:
    - GOOS=linux GOARCH=386
    - GOOS=linux GOARCH=amd64
script:
  - "make -f $GOOS_$GOARCH.Makefile dist"
  - "make -f $GOOS_$GOARCH.Makefile test-ft"
  - "make -f $GOOS_$GOARCH.Makefile test-ft-hb race"


