language: C
addons:
  apt:
    packages:
    - bzr
    - procps
    - g++
    - gcc
    - libc6-dev
    - make
    - pkg-config
compiler: gcc
before_script: apt-cache rdepends zlib1g
script: make dist-linux

